apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-api-pedidos-service
spec:
  # type: NodePort
  selector:
    app: tech-challenge-api-pedidos
  ports:
  - name: 3000-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  type: ClusterIP